export const travelIntentions = [
  { value: 'Toutes', label: 'Toutes', icon: '🌐', color: 'bg-gray-500' },
  { value: '50/50', label: '50/50', icon: '⚖️', color: 'bg-blue-500' },
  { value: 'Sponsor', label: 'Sponsor', icon: '💰', color: 'bg-green-500' },
  { value: 'Sponsorisé', label: 'Sponsorisé', icon: '🙏', color: 'bg-yellow-500' },
  { value: 'Groupe', label: 'Groupe', icon: '👥', color: 'bg-red-500' },
];

export const travelStyles = [
  { value: 'Tous', label: 'Tous', icon: '✈️' },
  { value: 'Aventure / Sac à dos', label: 'Aventure / Sac à dos', icon: '🎒' },
  { value: 'Luxe / Détente', label: 'Luxe / Détente', icon: '💎' },
  { value: 'Culturel / Historique', label: 'Culturel / Historique', icon: '🏛️' },
  { value: 'Festif / Événementiel', label: 'Festif / Événementiel', icon: '🎉' },
  { value: 'Religieux / Spirituel', label: 'Religieux / Spirituel', icon: '🕉️' },
  { value: 'Road Trip / Van Life', label: 'Road Trip / Van Life', icon: '🚐' },
  { value: 'Humanitaire / Écovolontariat', label: 'Humanitaire / Écovolontariat', icon: '❤️' },
  { value: 'Entre femmes', label: 'Entre femmes', icon: '🙋‍♀️' },
  { value: 'Entre hommes', label: 'Entre hommes', icon: '🙋‍♂️' },
  { value: 'Entre LGBT+', label: 'Entre LGBT+', icon: '🏳️‍🌈' },
  { value: 'Entre séniors', label: 'Entre séniors', icon: '👵' },
  { value: 'Entre jeunes', label: 'Entre jeunes', icon: '🤙' },
  { value: 'Autre', label: 'Autre', icon: '✨' },
];

export const travelActivities = [
  { value: 'Toutes', label: 'Toutes', icon: '🌟' },
  { value: 'Randonnée', label: 'Randonnée', icon: '🏞️' },
  { value: 'Plage', label: 'Plage', icon: '🏖️' },
  { value: 'Musées', label: 'Musées', icon: '🖼️' },
  { value: 'Concerts / Festivals', label: 'Concerts / Festivals', icon: '🎶' },
  { value: 'Gastronomie', label: 'Gastronomie', icon: '🍽️' },
  { value: 'Sorties nocturnes', label: 'Sorties nocturnes', icon: '🌃' },
  { value: 'Shopping', label: 'Shopping', icon: '🛍️' },
  { value: 'Yoga / Méditation', label: 'Yoga / Méditation', icon: '🧘' },
  { value: 'Sport', label: 'Sport', icon: '⚽' },
  { value: 'Pèlerinage', label: 'Pèlerinage', icon: '🕋' },
  { value: 'Soin et Santé', label: 'Soin et Santé', icon: '🏥' },
  { value: 'Chirurgie Esthétique', label: 'Chirurgie Esthétique', icon: '💉' },
  { value: 'Étude', label: 'Étude', icon: '📚' },
  { value: 'Travail', label: 'Travail', icon: '💼' },
  { value: 'Événement LGBT+', label: 'Événement LGBT+', icon: '🏳️‍🌈' },
  { value: 'Camping', label: 'Camping', icon: '🏕️' },
  { value: 'Autre', label: 'Autre', icon: '✨' },
];
